[package]
name = "drive_encryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onedrive-api = "0.10.0"
rouille = "3.6.2"
tokio = { version = "1", features = ["full"] }
